"""Unit tests for the phantom init command."""

from __future__ import annotations

from pathlib import Path

from click.testing import CliRunner

from phantom.cli import init


class TestInitCommand:
    def test_creates_manifest(self, tmp_path: Path) -> None:
        """init should create a .phantom.yml file."""
        runner = CliRunner()

        with runner.isolated_filesystem(temp_dir=tmp_path):
            result = runner.invoke(
                init,
                input="web\nmy-project\nMy Project\nnpm run dev\n3000\n2\n",
            )
            assert result.exit_code == 0
            assert "Created" in result.output
            assert ".phantom.yml" in result.output

            # Verify file was created
            manifest = Path(".phantom.yml")
            assert manifest.exists()

            content = manifest.read_text()
            assert 'project: "my-project"' in content
            assert 'name: "My Project"' in content
            assert "type: web" in content
            assert "capture-1" in content
            assert "capture-2" in content

    def test_generated_manifest_validates(self, tmp_path: Path) -> None:
        """The manifest generated by init should pass validation."""
        runner = CliRunner()

        with runner.isolated_filesystem(temp_dir=tmp_path):
            result = runner.invoke(
                init,
                input="web\ntest-app\nTest App\nnpm start\n8080\n1\n",
            )
            assert result.exit_code == 0

            # Load and validate the generated manifest
            from phantom.models import load_manifest

            manifest = load_manifest(".phantom.yml")
            assert manifest.project == "test-app"
            assert manifest.name == "Test App"
            assert len(manifest.captures) == 1
            assert manifest.captures[0].id == "capture-1"
            assert manifest.setup.type == "web"
            assert manifest.setup.run.ready_check.type == "http"
            assert "8080" in (manifest.setup.run.ready_check.url or "")

    def test_respects_overwrite_rejection(self, tmp_path: Path) -> None:
        """init should abort if user rejects overwriting existing file."""
        runner = CliRunner()

        with runner.isolated_filesystem(temp_dir=tmp_path):
            Path(".phantom.yml").write_text("existing content")

            result = runner.invoke(
                init,
                input="web\ntest\nTest\ncmd\n3000\n1\nn\n",
            )
            assert "Aborted" in result.output

            # File should not be changed
            assert Path(".phantom.yml").read_text() == "existing content"

    def test_overwrites_when_confirmed(self, tmp_path: Path) -> None:
        """init should overwrite when user confirms."""
        runner = CliRunner()

        with runner.isolated_filesystem(temp_dir=tmp_path):
            Path(".phantom.yml").write_text("old content")

            result = runner.invoke(
                init,
                input="web\ntest\nTest\ncmd\n3000\n1\ny\n",
            )
            assert result.exit_code == 0
            assert "Created" in result.output
            assert ".phantom.yml" in result.output
            assert Path(".phantom.yml").read_text() != "old content"

    def test_default_values(self, tmp_path: Path) -> None:
        """init with all defaults should still produce a valid manifest."""
        runner = CliRunner()

        with runner.isolated_filesystem(temp_dir=tmp_path):
            # Accept all defaults by pressing Enter repeatedly
            result = runner.invoke(
                init,
                input="\nmy-app\n\n\n\n\n",
            )
            assert result.exit_code == 0

            from phantom.models import load_manifest

            manifest = load_manifest(".phantom.yml")
            assert manifest.project == "my-app"
            assert len(manifest.captures) == 3  # Default

    def test_captures_count(self, tmp_path: Path) -> None:
        """init should create the requested number of captures."""
        runner = CliRunner()

        with runner.isolated_filesystem(temp_dir=tmp_path):
            result = runner.invoke(
                init,
                input="web\ntest\nTest\ncmd\n3000\n5\n",
            )
            assert result.exit_code == 0

            from phantom.models import load_manifest

            manifest = load_manifest(".phantom.yml")
            assert len(manifest.captures) == 5
            assert manifest.captures[4].id == "capture-5"
